export const data = [
    {
        name: '三站一场',
        count: 6,
        fid: 0,
        layer: 0,
        id: 1,
    },
    {
        name: '旅游景点',
        count: 8,
        layer: 0,
        fid: 0,
        id: 2,
    },
    {
        name: '汉江保护',
        count: 6,
        layer: 0,
        fid: 0,
        id: 3,
    },
    {
        name: '重点场所',
        count: 6,
        layer: 0,
        fid: 0,
        id: 4,
    },
    {
        name: '人员密集',
        count: 6,
        layer: 0,
        fid: 0,
        id: 5,
    },
    {
        name: '疫情防控',
        count: 8,
        layer: 0,
        fid: 0,
        id: 6,
    },
    {
        name: '进出城卡口',
        count: 6,
        layer: 0,
        fid: 0,
        id: 7,
    },
    {
        name: '共享单车',
        count: 8,
        layer: 0,
        fid: 0,
        id: 8,
    },
    {
        name: '燃气',
        count: 6,
        layer: 0,
        fid: 0,
        id: 9,
    },
    {
        name: '城市管理',
        count: 8,
        layer: 0,
        fid: 0,
        id: 10,
    },
    {
        name: '重点路口',
        count: 8,
        layer: 0,
        fid: 0,
        id: 11,
    },
    {
        name: '中心客运站周边',
        layer: 1,
        fid:1,
        id:12
    },
    {
        name: '旅游客运站周边',
        layer: 1,
        id:13,
        fid:1,
    },
    {
        layer: 1,
        name: '飞机场',
        id:14,
        fid:1,
    },
    {
        layer: 1,
        name: '飞机场1',
        id:17,
        fid:14,
    },
    {
        layer: 1,
        name: '飞机场4',
        id:20,
        fid:17,
    },
    {
        layer: 1,
        name: '飞机场2',
        id:18,
        fid:14,
    },
    {
        layer: 1,
        name: '飞机场3',
        id:19,
        fid:18,
    },
    {
        id:15,
        fid:13,
        layer: 2,
        name: '襄城客运站周边',
    },
    {
        id:16,
        layer: 2,
        fid:13,
        name: '襄阳火车站'
    },


]
