// data:
// {
//     title: '基础数据——河湖长履职数据统计表',
//     type: 2,
//     yarnData:[
//         {name:2022,value:2022},
//         {name:2021,value:2021},
//         {name:2020,value:2020},
//         {name:2019,value:2019},
//         {name:2018,value:2018},
//
//     ],
//     quarterData:[
//         {name:'1',value:1,hot:true},
//         {name:'2',value:2,hot:false},
//         {name:'3',value:3,hot:false},
//         {name:'4',value:4,hot:false},
//     ],
//     data: [
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//         {
//             xzqh:'保康县',
//             zrhhz:'11',
//             qb:'24',
//             hhzs:'27',
//             hhzqzxccs_qx:'21',
//             hhzqzxccs_jb:'5',
//             hhzqzxccs_xj:'26',
//             hhzqzxcrs_qx:'11',
//             hhzqzxcrs_jb:'1',
//             hhzqzxcrs_xj:'11',
//             wtxccs_qx:'11',
//             wtxccs_jb:'22',
//             wtxccs_xj:'33',
//             xczcs_qx:'32',
//             xczcs_jb:'27',
//             xczcs_xj:'59',
//             wbxchh:0,
//             wqzxcrs:0,
//             wxcqwwtxcrs:0,
//             hhzlzl_ylz:11,
//             hhzlzl_wlz:0,
//             hhzlzl_lzl:100,
//             lxbmlzl_ylz:26,
//             lxbmlzl_wlz:0,
//             lxbmlzl_lzl:100,
//             jjwtgs:65,
//         },
//
//     ]
// }

export default {
    title: '工作机制',
    type: 1,
    data: [

        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: 'http://10.203.4.240/xxzx_bank/sevp/2021/%E5%B8%82%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C%E5%8A%9E%E5%85%AC%E5%AE%A4%E5%85%B3%E4%BA%8E%E5%8D%B0%E5%8F%91%E8%A5%84%E9%98%B3%E5%B8%82%E6%8E%A8%E8%BF%9B%E6%B2%B3%E5%BA%93%E9%95%BF%E5%88%B6%E5%B7%A5%E4%BD%9C%E8%81%94%E5%B8%AD%E4%BC%9A%E8%AE%AE%E5%88%B6%E5%BA%A6%E7%9A%84%E9%80%9A%E7%9F%A5.pdf'
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },
        {
            name: '水利部、省政府河湖长制工作实施意见',
            url: ''
        },

    ]

}
//组织结构
// {
//     title: '襄城区河湖长制办公室组织结构',
//     type: 0,
//     data: ['余家湖街道办事处河湖长制办公室', '檀溪街道办事处河湖长制办公室', '卧龙镇河湖长制办公室', '欧庙镇河湖长制办公室', '古城街道办事处河湖长制办公室', '真武山街道办事处河湖长制办公室', '尹集乡河湖长制办公室', '隆中街道办事处河湖长制办公室', '庞龙街道办事处河湖长制办公室']
// }


// function(data, getLocalTempValue) {
//
//     return [
//         {
//             title: '基础数据——河湖长履职数据统计表',
//             type: 2,
//             yarnData:[
//                 {name:2022,value:2022},
//                 {name:2021,value:2021},
//                 {name:2020,value:2020},
//                 {name:2019,value:2019},
//                 {name:2018,value:2018},
//
//             ],
//             quarterData:[
//                 {name:'1',value:1,hot:true},
//                 {name:'2',value:2,hot:false},
//                 {name:'3',value:3,hot:false},
//                 {name:'4',value:4,hot:false},
//             ],
//             data: [
//                 {
//                     xzqh:'保康县',areaName
//                     zrhhz:'11', empCount
//                     qb:'24',allEmpCount
//                     hhzs:'27',allRvSegCount
//                     hhzqzxccs_qx:'21',ownPatrolAllCount
//                     hhzqzxccs_jb:'5',ownPatrollocalCount
//                     hhzqzxccs_xj:'26',ownPatrolSum
//                     hhzqzxcrs_qx:'11',ownPatrolAllCountEmp
//                     hhzqzxcrs_jb:'1',ownPatrollocalCountEmp
//                     hhzqzxcrs_xj:'11',ownPatrolSumEmp
//                     wtxccs_qx:'11',entrustPatrolAllCount
//                     wtxccs_jb:'22',entrustPatrollocalCount
//                     wtxccs_xj:'33',entrustPatrolSum
//                     xczcs_qx:'32',patrolAllSum
//                     xczcs_jb:'27',patrollocalSum
//                     xczcs_xj:'59',patrolSum
//                     wbxchh:0,noPatrolRvSegCount
//                     wqzxcrs:0,noOwnPatrolCount
//                     wxcqwwtxcrs:0,noPatrolAndnoEntrustCount
//                     hhzlzl_ylz:11,lvZhiHeZhangEmpCount
//                     hhzlzl_wlz:0,notLvZhiHeZhangEmpCount
//                     hhzlzl_lzl:100,lvZhiRate
//                     lxbmlzl_ylz:26,lvZhiOrgEmpCount
//                     lxbmlzl_wlz:0,notLvZhiOrgEmpCount
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,prProblem
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//                 {
//                     xzqh:'保康县',
//                     zrhhz:'11',
//                     qb:'24',
//                     hhzs:'27',
//                     hhzqzxccs_qx:'21',
//                     hhzqzxccs_jb:'5',
//                     hhzqzxccs_xj:'26',
//                     hhzqzxcrs_qx:'11',
//                     hhzqzxcrs_jb:'1',
//                     hhzqzxcrs_xj:'11',
//                     wtxccs_qx:'11',
//                     wtxccs_jb:'22',
//                     wtxccs_xj:'33',
//                     xczcs_qx:'32',
//                     xczcs_jb:'27',
//                     xczcs_xj:'59',
//                     wbxchh:0,
//                     wqzxcrs:0,
//                     wxcqwwtxcrs:0,
//                     hhzlzl_ylz:11,
//                     hhzlzl_wlz:0,
//                     hhzlzl_lzl:100,
//                     lxbmlzl_ylz:26,
//                     lxbmlzl_wlz:0,
//                     lxbmlzl_lzl:100,
//                     jjwtgs:65,
//                 },
//
//             ]
//
//         }
//     ]
//
//
//     return data;
// }
function a(data, getLocalTempValue) {

    let months = [1,3,5,7,8,10,12];//有31的月份

    const endDate = new Date();
    const endY = endDate.getFullYear();
    let endTime = '';
    let startTime = '';
    let years = [];
    let mount = [];
    let year = 0;
    let M = 0;
    let jidu = endDate.getMonth() + 1;
    if(jidu>=1&&jidu<=3){
        startTime = `${endY-1}-10-01`;
        endTime =  `${endY-1}-12-31`;
        year = endY-1;
        M = 4;
    }else if(jidu>3&&jidu<=6){
        year = endY;
        startTime = `${endY}-01-01`;
        endTime =  `${endY}-03-31`;
        M = 1;
        //属于第二季度
    }else if(jidu>6&&jidu<=9){
        //属于第三季度
        year = endY;
        startTime = `${endY}-04-01`;
        endTime =  `${endY}-06-30`;
        M = 2;
    }else if(jidu>9&&jidu<=12){
        //属于第四季度
        year = endY;
        startTime = `${endY}-07-01`;
        endTime =  `${endY}-09-30`;
        M = 3;
    }



    for(let i=0;i<5;i++){
        let obj = {};
        obj.name = endY-i;
        obj.value=endY-i;
        if(obj.value==year){
            obj.hot=true;
        }else{
            obj.hot=false;
        }
        years.push(obj)
    }

    for(let i = 0; i<4; i++){
        let obj = {};
        obj.name = (i+1);
        obj.value = (i+1);
        if(obj.value == M){
            obj.hot = true;
        }else {
            obj.hot = false;
        }
        mount.push(obj);
    }


    return [{name:'jcmount',value:mount},{name:'jcyears',value:years},{name:'jcStime',value:startTime},{name:'jcEndTime',value:endTime}]
}
